# Generated by Django 4.0.4 on 2022-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercar',
            name='first_reg',
            field=models.CharField(max_length=8),
        ),
    ]
